<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUfp7d5z\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUfp7d5z/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUfp7d5z.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUfp7d5z\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUfp7d5z\appProdProjectContainer([
    'container.build_hash' => 'Ufp7d5z',
    'container.build_id' => 'd5fc86fe',
    'container.build_time' => 1632047527,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUfp7d5z');
